name: events-backend-group
services:

  events-backend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        CACHE_BUST: ${CACHE_BUST}
    hostname: events-backend
    container_name: events-backend
    ports:
      - 43546:8855
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://events-backend-db/events-backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - events-backend-network


  events-backend-db:
    mem_limit: 256m
    cpus: '0.5'
    image: postgres:10.23-alpine3.16
    hostname: events-backend-db
    container_name: events-backend-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events-backend
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./_db/events-backend:/var/lib/postgresql/data
    ports:
      - 5455:5432
    networks:
      - events-backend-network
    restart: unless-stopped


networks:
  events-backend-network:
    driver: bridge
