name: events-backend-group
services:

  events-backend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        CACHE_BUST: ${CACHE_BUST}
    hostname: events-backend
    container_name: events-backend
    ports:
      - 43546:8855
    volumes:
      - ./_files_storage:/_files_storage
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://events-backend-db/events-backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - APPLICATION_ADMIN_EMAIL=${ADMIN_EMAIL}
      - APPLICATION_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APPLICATION_ADMIN_NAME=${ADMIN_NAME}
      - APPLICATION_CREATOR_EMAIL=${CREATOR_EMAIL}
      - APPLICATION_CREATOR_PASSWORD=${CREATOR_PASSWORD}
      - APPLICATION_CREATOR_NAME=${CREATOR_NAME}
      - APPLICATION_FILES_STORAGE=/_files_storage
    networks:
      - events-backend-network
    restart: unless-stopped


  events-backend-db:
    mem_limit: 1024m
    cpus: '1'
    image: postgres:10.23-alpine3.16
    hostname: events-backend-db
    container_name: events-backend-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events-backend
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./_db/events-backend:/var/lib/postgresql/data
    ports:
      - 5455:5432
    networks:
      - events-backend-network
    restart: unless-stopped


networks:
  events-backend-network:
    driver: bridge
