server:
  port: 8855
spring:
  application:
    name: events-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  config:
    # You must create your 'firebase.yml' file and place it near 'application.yml'.
    # You can view 'firebase-example.yml' as a formatting example
    import: optional:classpath:firebase.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/events-backend
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

com:
  behl:
    flare:
      open-api:
        enabled: true
        api-version: 1.0.0
        title: Events-Service-Backend
        description: Backend application integrating with firebase authentication and storage service to build a secure CRUD application

